INSERT INTO `roles` (`name`, `slug`,  `description`, `createdAt`, `updatedAt`, `deletedAt`, `is_active`, `is_admin`, `is_super_admin`) 
VALUES('Administrator', 'administrator','Administrator', now(), now(), NULL, '1', '1', '1'),
('Event Organizer', 'event-oraganizer', 'Event Oraganizer', now(), now(), NULL, '1', '0', '0'),
('Audience', 'audience', 'Audience', now(), now(), NULL, '1', '0', '0');
INSERT INTO `users` (`first_name`, `last_name`, `password`, `gender`, `dob`, `email`, `area_code`, `mobile_no`, `address_1`, `address_2`, `role_id`, `city`, `state`, `pincode`, `country`, `createdAt`, `updatedAt`, `deletedAt`, `is_active`)
VALUES('admin', 'a', '$2b$04$a5xX4zSNe7/nB7WDuyQHS.HiWJ/tD5Q7JrhZuJaVn/71wWgE73BKm', '1', '1994-12-22', 'admin@event.com', '+91', '9791447542', 'address 1', 'address 2', '1', 'chennai', 'TN', '600004', 'India', now(), now(), NULL, '1');

INSERT INTO `currencies` (`name`, `code`,  `createdAt`, `is_active`) VALUES
('USD', 'usd', now(), '1'),
('EUR', 'eur', now(), '1'),
('INR', 'inr', now(), '1'),
('GBP', 'gbp', now(), '1'),
('JPY', 'jpy', now(), '1'),
('CHF', 'chf', now(), '1'),
('CAD', 'cad', now(), '1'),
('AUD', 'aud', now(), '1'),
('SGD', 'sgd', now(), '1'),

('AED', 'aed', now(), '0'),
('AFN', 'afn', now(), '0'),
('ALL', 'all', now(), '0'),
('AMD', 'amd', now(), '0'),
('ANG', 'ang', now(), '0'),
('AOA', 'aoa', now(), '0'),
('ARS', 'ars', now(), '0'),
('AWG', 'awg', now(), '0'),
('AZN', 'azn', now(), '0'),
('BAM', 'bam', now(), '0'),
('BBD', 'bbd', now(), '0'),
('BDT', 'btd', now(), '0'),
('BGN', 'bgn', now(), '0'),
('BIF', 'bif', now(), '0'),
('BMD', 'bmd', now(), '0'),
('BND', 'bnd', now(), '0'),
('BOB', 'bob', now(), '0'),
('BRL', 'brl', now(), '0'),
('BSD', 'bsd', now(), '0'),
('BWP', 'bwp', now(), '0'),
('BZD', 'bzd', now(), '0'),
('CDF', 'cdf', now(), '0'),
('CLP', 'clp', now(), '0'),
('CNY', 'cny', now(), '0'),
('COP', 'cop', now(), '0'),
('CRC', 'crc', now(), '0'),
('CVE', 'cve', now(), '0'),
('CZK', 'czk', now(), '0'),
('DJF', 'djf', now(), '0'),
('DKK', 'dkk', now(), '0'),
('DOP', 'dop', now(), '0'),
('DZD', 'dzd', now(), '0'),
('EGP', 'egp', now(), '0'),
('ETB', 'etb', now(), '0'),
('FJD', 'fjd', now(), '0'),
('FKP', 'fkp', now(), '0'),
('GEL', 'gel', now(), '0'),
('GIP', 'gip', now(), '0'),
('GMD', 'gmd', now(), '0'),
('GNF', 'gnf', now(), '0'),
('GTQ', 'gtq', now(), '0'),
('GYD', 'gyd', now(), '0'),
('HKD', 'hkd', now(), '0'),
('HNL', 'hnl', now(), '0'),
('HRK', 'hrk', now(), '0'),
('HTG', 'htg', now(), '0'),
('HUF', 'huf', now(), '0'),
('IDR', 'idr', now(), '0'),
('ILS', 'ils', now(), '0'),
('ISK', 'isk', now(), '0'),
('JMD', 'jmd', now(), '0'),
('KES', 'kes', now(), '0'),
('KGS', 'kgs', now(), '0'),
('KHR', 'khr', now(), '0'),
('KMF', 'kmf', now(), '0'),
('KRW', 'krw', now(), '0'),
('KYD', 'kyd', now(), '0'),
('KZT', 'kzt', now(), '0'),
('LAK', 'lak', now(), '0'),
('LBP', 'lbp', now(), '0'),
('LKR', 'lkr', now(), '0'),
('LRD', 'lrd', now(), '0'),
('LSL', 'lsl', now(), '0'),
('MAD', 'mad', now(), '0'),
('MDL', 'mdl', now(), '0'),
('MGA', 'mga', now(), '0'),
('MKD', 'mkd', now(), '0'),
('MMK', 'mmk', now(), '0'),
('MNT', 'mnt', now(), '0'),
('MOP', 'mop', now(), '0'),
('MRO', 'mro', now(), '0'),
('MUR', 'mur', now(), '0'),
('MVR', 'mvr', now(), '0'),
('MWK', 'mwk', now(), '0'),
('MXN', 'mxn', now(), '0'),
('MYR', 'myr', now(), '0'),
('MZN', 'myn', now(), '0'),
('NAD', 'nad', now(), '0'),
('NGN', 'ngn', now(), '0'),
('NIO', 'nio', now(), '0'),
('NOK', 'nok', now(), '0'),
('NPR', 'npr', now(), '0'),
('NZD', 'nzd', now(), '0'),
('PAB', 'pab', now(), '0'),
('PEN', 'pen', now(), '0'),
('PGK', 'pgk', now(), '0'),
('PHP', 'php', now(), '0'),
('PKR', 'pkr', now(), '0'),
('PLN', 'pln', now(), '0'),
('PYG', 'pyg', now(), '0'),
('QAR', 'qar', now(), '0'),
('RON', 'ron', now(), '0'),
('RSD', 'rsd', now(), '0'),
('RUB', 'rub', now(), '0'),
('RWF', 'rwf', now(), '0'),
('SAR', 'sar', now(), '0'),
('SBD', 'sbd', now(), '0'),
('SCR', 'scr', now(), '0'),
('SEK', 'sek', now(), '0'),
('SHP', 'shp', now(), '0'),
('SLL', 'sll', now(), '0'),
('SOS', 'sos', now(), '0'),
('SRD', 'srd', now(), '0'),
('STD', 'std', now(), '0'),
('SZL', 'szl', now(), '0'),
('THB', 'thb', now(), '0'),
('TJS', 'tjs', now(), '0'),
('TOP', 'top', now(), '0'),
('TRY', 'try', now(), '0'),
('TTD', 'ttd', now(), '0'),
('TWD', 'twd', now(), '0'),
('TZS', 'tzs', now(), '0'),
('UAH', 'uah', now(), '0'),
('UGX', 'ugx', now(), '0'),
('UYU', 'uyu', now(), '0'),
('UZS', 'uns', now(), '0'),
('VND', 'vnd', now(), '0'),
('VUV', 'vuv', now(), '0'),
('WST', 'wst', now(), '0'),
('XAF', 'xaf', now(), '0'),
('XCD', 'xcd', now(), '0'),
('XOF', 'xof', now(), '0'),
('XPF', 'xpf', now(), '0'),
('YER', 'yer', now(), '0'),
('ZAR', 'zar', now(), '0'),
('ZMW', 'zmw', now(), '0');


INSERT INTO `pages` (`name`, `slug`, `content`, `meta_title`, `meta_description`, `meta_keywords`, `is_active`, `createdAt`, `updatedAt`, `deletedAt`)
VALUES ('About Us', 'about-us', 'About Us', 'About Us', 'About Us', 'About Us', '1', now(), NULL, NULL);

INSERT INTO `pages` (`name`, `slug`, `content`, `meta_title`, `meta_description`, `meta_keywords`, `is_active`, `createdAt`, `updatedAt`, `deletedAt`)
VALUES ('Terms And Conditions', 'terms-and-conditions', 'Terms And Conditions Content', 'Terms And Conditions', 'Terms And Conditions', 'Terms And Conditions', '1', now(), NULL, NULL);
INSERT INTO `pages` (`name`, `slug`, `content`, `meta_title`, `meta_description`, `meta_keywords`, `is_active`, `createdAt`, `updatedAt`, `deletedAt`)
VALUES ('Privacy Policy', 'privacy-policy', 'Privacy Policy', 'Privacy Policy', 'Privacy Policy', 'Privacy Policy', '1', now(), NULL, NULL);
INSERT INTO `pages` (`name`, `slug`, `content`, `meta_title`, `meta_description`, `meta_keywords`, `is_active`, `createdAt`, `updatedAt`, `deletedAt`)
VALUES ('FAQ', 'faq', 'faq', 'faq', 'faq', 'Faq', '1', now(), NULL, NULL);